export const CANVAS = {
  STEP_ADVANCED: 'STEP_ADVANCED',
  STEP_RETREATED: 'STEP_RETREATED',
  STEP_RESETED: 'STEP_RESETED'
};

export const DATA = {
  LOADED: 'LOADED',
  SWITCHED_LANGUAGE: 'WSWITCHED_LANGUAGE'
};
