export const CANVAS = {
  STEP_ADVANCED: 'STEP_ADVANCED',
  STEP_RETREATED: 'STEP_RETREATED',
  STEP_CHANGED: 'STEP_CHANGED',
  HELP_ACTIVATED: 'HELP_ACTIVATED',
  HELP_DEACTIVATED: 'HELP_DEACTIVATED',
  RESET: 'RESET'
};

export const DATA = {
  LOADED: 'LOADED',
  SWITCHED_LANGUAGE: 'WSWITCHED_LANGUAGE'
};
