export const CANVAS = {
  STEP_ADVANCED: 'STEP_ADVANCED',
  STEP_RETREATED: 'STEP_RETREATED',
  STEP_CHANGED: 'STEP_CHANGED',
  HELP_ACTIVATED: 'HELP_ACTIVATED',
  HELP_DEACTIVATED: 'HELP_DEACTIVATED',
  CHARACTER_SELECTED: 'CHARACTER_SELECTED',
  CHARACTER_DRESSED: 'CHARACTER_DRESSED',
  WEAPON_SELECTED: 'WEAPON_SELECTED',
  ACCESSORY_ADDED: 'ACCESSORY_ADDED',
  ACCESSORY_UPDATED: 'ACCESSORY_UPDATED',
  ACCESSORY_REORDERED: 'ACCESSORY_REORDERED',
  ACCESSORY_FLIPPED: 'ACCESSORY_FLIPPED',
  ACCESSORY_REMOVED: 'ACCESSORY_REMOVED',
  SAVING_REQUESTED: 'SAVE_REQUESTED',
  SAVING_DONE: 'SAVING_DONE',
  SAVING_FAILED: 'SAVING_FAILED',
  FUNFACT_CHOSEN: 'FUNFACT_CHOSEN',
  FUNFACT_DISCARDED: 'FUNFACT_DISCARDED',
  RESET: 'RESET'
};

export const DATA = {
  LOADED: 'LOADED',
  SWITCHED_LANGUAGE: 'WSWITCHED_LANGUAGE'
};

export const OUTFIT = {
  FILTER_CHANGED: 'FILTER_CHANGED',
  ITEM_DRAGGED: 'ITEM_DRAGGED',
  ITEM_DROPPED: 'ITEM_DROPPED'
};

export const ACCESSORIZE = {
  ACCESSORY_DRAGGED: 'ACCESSORY_DRAGGED',
  ACCESSORY_DROPPED: 'ACCESSORY_DROPPED'
};

export const FINISH = {
  STEP_ADVANCED: 'STEP_ADVANCED',
  NAME_SET: 'NAME_SET',
  EMAIL_SET: 'EMAIL_SET',
  BG_SET: 'BG_SET',
  SAVING_REQUESTED: 'SAVING_REQUESTED',
  FINISH_DONE: 'FINISH_DONE',
  FINISH_FAILED: 'FINISH_FAILED'
};
